/*
 * Squidex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.squidex.api.types;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.squidex.api.types.ResourceLink;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.squidex.api.core.JSON;

/**
 * ContributorDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0-SNAPSHOT")
public class ContributorDto {
  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Map<String, ResourceLink> links = new HashMap<>();
  public static final String SERIALIZED_NAME_CONTRIBUTOR_ID = "contributorId";
  @SerializedName(SERIALIZED_NAME_CONTRIBUTOR_ID)
  private String contributorId;
  public static final String SERIALIZED_NAME_CONTRIBUTOR_NAME = "contributorName";
  @SerializedName(SERIALIZED_NAME_CONTRIBUTOR_NAME)
  private String contributorName;
  public static final String SERIALIZED_NAME_CONTRIBUTOR_EMAIL = "contributorEmail";
  @SerializedName(SERIALIZED_NAME_CONTRIBUTOR_EMAIL)
  private String contributorEmail;
  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  private String role;
  public ContributorDto() {
  }
  public ContributorDto links(Map<String, ResourceLink> links) {
    this.links = links;
    return this;
  }

  public ContributorDto putLinksItem(String key, ResourceLink linksItem) {
    if (this.links == null) {
      this.links = new HashMap<>();
    }
    this.links.put(key, linksItem);
    return this;
  }

  /**
   * The links.
   * @return links
   */
  @javax.annotation.Nonnull
  public Map<String, ResourceLink> getLinks() {
    return links;
  }

  public void setLinks(Map<String, ResourceLink> links) {
    this.links = links;
  }
  public ContributorDto contributorId(String contributorId) {
    this.contributorId = contributorId;
    return this;
  }

  /**
   * The ID of the user that contributes to the app.
   * @return contributorId
   */
  @javax.annotation.Nonnull
  public String getContributorId() {
    return contributorId;
  }

  public void setContributorId(String contributorId) {
    this.contributorId = contributorId;
  }
  public ContributorDto contributorName(String contributorName) {
    this.contributorName = contributorName;
    return this;
  }

  /**
   * The display name.
   * @return contributorName
   */
  @javax.annotation.Nonnull
  public String getContributorName() {
    return contributorName;
  }

  public void setContributorName(String contributorName) {
    this.contributorName = contributorName;
  }
  public ContributorDto contributorEmail(String contributorEmail) {
    this.contributorEmail = contributorEmail;
    return this;
  }

  /**
   * The email address.
   * @return contributorEmail
   */
  @javax.annotation.Nonnull
  public String getContributorEmail() {
    return contributorEmail;
  }

  public void setContributorEmail(String contributorEmail) {
    this.contributorEmail = contributorEmail;
  }
  public ContributorDto role(String role) {
    this.role = role;
    return this;
  }

  /**
   * The role of the contributor.
   * @return role
   */
  @javax.annotation.Nullable
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContributorDto contributorDto = (ContributorDto) o;
    return Objects.equals(this.links, contributorDto.links) &&
        Objects.equals(this.contributorId, contributorDto.contributorId) &&
        Objects.equals(this.contributorName, contributorDto.contributorName) &&
        Objects.equals(this.contributorEmail, contributorDto.contributorEmail) &&
        Objects.equals(this.role, contributorDto.role);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, contributorId, contributorName, contributorEmail, role);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContributorDto {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    contributorId: ").append(toIndentedString(contributorId)).append("\n");
    sb.append("    contributorName: ").append(toIndentedString(contributorName)).append("\n");
    sb.append("    contributorEmail: ").append(toIndentedString(contributorEmail)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("_links");
    openapiFields.add("contributorId");
    openapiFields.add("contributorName");
    openapiFields.add("contributorEmail");
    openapiFields.add("role");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("_links");
    openapiRequiredFields.add("contributorId");
    openapiRequiredFields.add("contributorName");
    openapiRequiredFields.add("contributorEmail");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ContributorDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContributorDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContributorDto is not found in the empty JSON string", ContributorDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContributorDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContributorDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ContributorDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("contributorId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contributorId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contributorId").toString()));
      }
      if (!jsonObj.get("contributorName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contributorName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contributorName").toString()));
      }
      if (!jsonObj.get("contributorEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contributorEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contributorEmail").toString()));
      }
      if ((jsonObj.get("role") != null && !jsonObj.get("role").isJsonNull()) && !jsonObj.get("role").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `role` to be a primitive type in the JSON string but got `%s`", jsonObj.get("role").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContributorDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContributorDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContributorDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContributorDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ContributorDto>() {
           @Override
           public void write(JsonWriter out, ContributorDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContributorDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ContributorDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ContributorDto
   * @throws IOException if the JSON string is invalid with respect to ContributorDto
   */
  public static ContributorDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContributorDto.class);
  }

  /**
   * Convert an instance of ContributorDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
