plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.diffplug.spotless' version '8.9.0'
    id "com.vanniktech.maven.publish" version "0.37.0"
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    api 'com.google.code.findbugs:jsr305:3.0.2'
    api 'javax.annotation:javax.annotation-api:1.3.2'
    api 'com.google.code.gson:gson:2.14.0'
    api 'com.squareup.okhttp3:logging-interceptor:5.4.0'
    api 'com.squareup.okhttp3:okhttp:5.4.0'
    api 'io.gsonfire:gson-fire:1.9.0'
    api 'io.swagger:swagger-annotations:1.6.16'
    api 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    api 'jakarta.ws.rs:jakarta.ws.rs-api:4.0.0'
    api 'org.openapitools:jackson-databind-nullable:0.2.11'
    testImplementation platform('org.junit:junit-bom:6.1.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

spotless {
    java {
        palantirJavaFormat()
    }
}

javadoc {
    options.tags = ["http.response.details:a:Http Response Details"]

    if (JavaVersion.current().isJava8Compatible()) {
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}

mavenPublishing {
  publishToMavenCentral()

  coordinates("io.squidex", "squidex", "2.0.0-RC1")

  pom {
    name = "Squidex SDK"
    description = "Client Library for the Squidex API"
    inceptionYear = "2020"
    url = "https://github.com/squidex/sdk-java"
    licenses {
      license {
        name = "MIT"
      }
    }
    developers {
      developer {
        id = "sebastianstehle"
        name = "Sebastian Stehle"
        url = "https://github.com/sebastianstehle/"
      }
    }
     scm {
      url = "https://github.com/squidex/squidex/"
      connection = "scm:git:git://github.com/squidex/squidex.git"
      developerConnection = "scm:git:ssh://git@github.com/squidex/squidex.git"
    }
  }

  signAllPublications()
}

