/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squidex.api.resources.assets.requests;

import com.squidex.api.core.ObjectMappers;

public final class AssetsPutAssetContentRequest {
    private AssetsPutAssetContentRequest() {}

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AssetsPutAssetContentRequest;
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }
}
