name: Check Update
concurrency: check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Check for Update
        uses: saadmk11/github-actions-version-updater@v0.7.4
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
          release_types: 'major'
