name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v4.2.2
        with:
          java-version: "11"
          architecture: x64
          distribution: oracle

      - name: Compile
        run: ./gradlew compileJava

      - name: Test - Start Compose
        run: docker compose up -d
        working-directory: tests

      - name: Test - RUN
        run: ./gradlew test
        env:
          CONFIG__WAIT: 60
          CONFIG__SERVER__URL: http://localhost:8080
        working-directory: .
       
      - name: Test - Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2.2.1
        with:
         images: 'squidex/squidex,squidex/resizer'
         tail: '100'

      - name: Test - Cleanup
        if: always()
        run: docker compose down
        working-directory: tests

      - name: Publish to maven
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_PUBLISH_REGISTRY_URL: "https://s01.oss.sonatype.org/content/repositories/releases/"
